dimagi/dimagi.com

dimagi/sectors/data/countries.py, dimagi/sectors/data/sectors/__init__.py, dimagi/sectors/data/sectors/hiv_aids.py, dimagi/sectors/templates/sectors/content/hiv_aids.html, dimagi/sectors/templates/sectors/content/hiv_aids/clinics_and_clinicians.html, dimagi/sectors/templates/sectors/content/hiv_aids/community_health_workers.html
no - Additional Resources - section
Case Study moved from Additional Resources to Case Studies section
=> 270467 Dimagi.com Sector: HIV/AIDS

dimagi/sectors/data/countries.py, dimagi/sectors/data/sectors/__init__.py, dimagi/sectors/data/sectors/tuberculosis.py, dimagi/sectors/templates/sectors/content/tuberculosis.html, dimagi/sectors/templates/sectors/content/tuberculosis/health_workers.html, dimagi/sectors/templates/sectors/content/tuberculosis/tb_patients.html, dimagi/sectors/templates/sectors/content/tuberculosis/tb_programs_and_clinics.html
No - additional resources section
=> 271067 Dimagi.com Sector: Tuberculosis

dimagi/sectors/data/sectors/agricultural_cooperatives.py, dimagi/sectors/data/sectors/agricultural_finance.py, dimagi/sectors/data/sectors/agriculture_extension_programs.py, dimagi/sectors/data/sectors/child_health.py, dimagi/sectors/data/sectors/ebola_response.py, dimagi/sectors/data/sectors/education.py, dimagi/sectors/data/sectors/gender_based_violence.py, dimagi/sectors/data/sectors/hiv_aids.py, dimagi/sectors/data/sectors/humanitarian_response.py, dimagi/sectors/data/sectors/logistics.py, dimagi/sectors/data/sectors/mlabor.py, dimagi/sectors/data/sectors/nutrition.py, dimagi/sectors/data/sectors/programmatic_research.py, dimagi/sectors/models.py, dimagi/sectors/templates/sectors/sections/additional_resources.html, dimagi/sectors/templates/sectors/view_single.html
@biyeun I have removed the tracking from URL that I've been able to recognize that there is tracking in it. Like: The part
"?__hstc=240960668.41b1f79d5eb5c17e0c46e4237991c19b.1518524627256.1519222868199.1519297574541.29&__hssc=240960668.25.1519297574541&__hsfp=49117607"
from: 
https://www.commcarehq.org/exchange/145d386993f5b6cf40f1ba96bdb961a3/info/?__hstc=240960668.41b1f79d5eb5c17e0c46e4237991c19b.1518524627256.1519222868199.1519297574541.29&__hssc=240960668.25.1519297574541&__hsfp=49117607
But I think that links would need a double check since I'm coping the content from dimagi.com web page not from CMS
=> 270455 additional resources

.travis.yml
Note: The repo is not yet enabled in Travis.
=> Initial Travis configuration. 

dimagi/pages/templates/base.html, dimagi/pages/templates/partials/schedule_demo_button.html, dimagi/pages/views/commcare.py, dimagi/pages/views/core.py, dimagi/styleguide/templates/styleguide/_base.html, dimagi/utils/ab_tests.py
remove drift variant
serve two different hubspot forms based on A/B result
=> Implement V2 of Demo Workflow A/B Test

dimagi/pages/templates/sections/commcare/product/overview.html
Typo from Comacare to Commcare
=> Typo fixes

Pipfile, Pipfile.lock
=> Revert "update pipenv"

dimagi/pages/templates/sections/careers/open_positions.html
Added CTA button in careers page as general application
=> Added cta in careers page

dimagi/pages/templates/sections/open_source/open_source_home/community/developer_forum.html, dimagi/pages/templates/sections/open_source/open_source_home/community/user_forum.html
:man_facepalming: 
would be good if we can deploy this asap
=> fix typos in "forum"

dimagi/pages/templates/sections/commcare/product_features/overview/clean.html
Updated language in commcare features page
=> Features page typo on "inspect form submissions"

dimagi/pages/models/careers.py, dimagi/pages/static/js/careers/list.js, dimagi/pages/templates/pages/job.html, dimagi/pages/templates/sections/job/description.html
https://dimagi-dev.atlassian.net/browse/SAAS-11350
=> Re-implement Locations in Careers

dimagi/data/commcare/pricing/__init__.py, dimagi/data/commcare/pricing/enterprise_web_apps.py, dimagi/data/commcare/pricing/user_management.py
Added a new section to existing Plans on the CommCare pricing page.
=> New section to existing Plans

dimagi/pages/templates/sections/team/office.html, dimagi/pages/templates/sections/team/sub_nav.html
Sorted alphabetically office list in the nav bar for the Team page.
=> Sorted office list for team page

dimagi/pages/templates/sections/commcare/product/research.html
Updated copy in CommCare Product Page under TRUST COMMCARE Section.
=> Updated copy in CommCare Product Page

dimagi/pages/templates/partials/footer/nav_section/commcare_menu.html
Added CommCare for Research and CommCare for M&E in the footer.
=> Added footer links

dimagi/pages/templates/sections/pillar/community_health_worker/chapter7/video.html
Updated copy in CHW pillar page for 7th section
=> CHW pillar page copy update

dimagi/pages/templates/sections/sectors/maternal_and_child_health/overview.html
- Copy update in Maternal & Child Health Sector page
=> Updated copy

dimagi/pages/templates/pages/commcare/product.html, dimagi/pages/templates/sections/commcare/product/overview.html
Updated Product page demo video URL.
=> Product page video link update

dimagi/urls.py
Created redirect from:
dimagi.com/cloudworks
to:
cloudworks.dimagi.com/landing
=> Added redirect link to cloudworks

dimagi/data/case_studies/mhealth/egpaf_baylor_hiv_tracking.py, dimagi/pages/templates/pages/case_studies/view_single.html
Added new copy and Title updates to EGPAF Case study.
=> Added new copy updates

dimagi/pages/templates/pages/blog/home.html
Copy update in Blog page(Title and Heading).
=> Updated copy in blog page

dimagi/pages/static/style/pages/commcare/research.scss, dimagi/pages/templates/base.html, dimagi/pages/templates/pages/focus_mdm/pricing.html, dimagi/pages/templates/sections/commcare/product_onboarding/package.html, dimagi/pages/templates/sections/commcare/research/case_studies.html, dimagi/pages/templates/sections/commcare/research/features/collect.html, dimagi/pages/templates/sections/commcare/research/features/protocol.html, dimagi/pages/templates/sections/commcare/research/features/secure.html, dimagi/pages/templates/sections/commcare/research/onboarding.html, dimagi/pages/templates/sections/commcare/research/projects.html, dimagi/pages/templates/sections/covid_19/resources/vaccine-delivery.html
Added feedback changes to 
1) Research page
2) Focus MDM page
=> Feedback changes

assets/style/app/variables/_colors.scss, dimagi/pages/models/blog.py, dimagi/pages/static/style/pages/blog.scss, dimagi/pages/templates/pages/blog/archive.html, dimagi/pages/templates/pages/blog/post.html, dimagi/pages/templates/partials/social.html, dimagi/pages/templates/sections/blog/full_post.html, dimagi/pages/templates/sections/blog/sub_nav.html, dimagi/pages/templates/svg/blog/icon/blog_authors.html, dimagi/pages/urls/blog.py, dimagi/pages/views/blog.py, dimagi/utils/wordpress_api.py
The first part of change requests for https://dimagi-dev.atlassian.net/browse/SS-197
This addresses style changes for a single blog post.
Also added is backend support for searching blog posts based on the following criteria:
- category
- tag(s)
- search term
- dates
next PR will cover UI support for searching our blog posts
=> Blog updates
